services:
  redis:
    image: redis:8.4.0
    container_name: urlshortener-redis
    ports:
      - "6379:6379"
    networks:
      - urlshortener-net

  cassandra:
    image: cassandra:5.0
    container_name: urlshortener-cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: urlshortener-cluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - urlshortener-net

volumes:
  cassandra-data:

networks:
  urlshortener-net:
    driver: bridge