package org.abondar.experimental.urlshortner.config

import io.ktor.server.routing.get
import io.ktor.server.routing.post
import io.ktor.server.application.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import org.abondar.experimental.urlshortner.exception.UrlRequestException
import org.abondar.experimental.urlshortner.model.ShortenRequest
import org.abondar.experimental.urlshortner.model.ShortenResponse
import org.abondar.experimental.urlshortner.service.UrlShortenerService
import org.kodein.di.instance
import org.kodein.di.ktor.closestDI


fun Application.configureRouting() {

    val urlShortenerService by closestDI().instance<UrlShortenerService>()

    routing {

        /**
         * Generate short url from long
         *
         * Body: application/json
         * [ShortenRequest]
         *
         * Responses:
         * - 200: short url [ShortenResponse]
         * - 400: Provided url is blank or empty
         */
        post("/shorten") {
            val request = call.receive<ShortenRequest>()
            val longUrl = request.url

            val shortUrl = urlShortenerService.shortenUrl(longUrl)

            call.respond(ShortenResponse(shortUrl))
        }

        /**
         * Find long url from short and redirect to it
         *
         * Path: shortUrl generated by service shortUrl
         * Responses
         * - 302 - redirect to long url
         * - 404: Provided url is not found
         */
        get("/{shortUrl}") {
            val shortUrl = call.parameters["shortUrl"] ?: throw UrlRequestException("Url parameter is required")
            val longUrl = urlShortenerService.getLongUrl(shortUrl)

            call.respondRedirect(longUrl)

        }
    }
}
